sudo: false
language: ruby
rvm:
  - 2.2.4
before_install:
  - rvm use @global
  - gem uninstall bundler -x || gem uninstall bundler -a || true
  - gem install bundler -v 1.17.3
  - bundler --version
script:
  - rvm use @global
  - bundle exec rake
jobs:
  include:
    - stage: gem release
      rvm: 2.2.4
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key:
          secure: AzTHDbKRr1ZO4E2mRyvU054Tx8c2cZbKkoDBZjSAQ2CY3E7oH137NTAIGd4BthH/E9mbEXtGpZIDfWPbaOcUJQ5Bz24CWTKmGyic6FrPhJnOW5CKVSLGCDPzpmqHULv/GTN16YN0Dh1HLeGYZzlHlxT0+4AVvbvBAleHrAFeJs8=
        gem: pact-message
        on:
          tags: true
          repo: pact-foundation/pact-message-ruby
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6523128341fad111ed79
    on_success: change
    on_failure: always
    on_start: never
