sudo: false
language: ruby
rvm:
  - 2.2.4
before_install:
  - rvm use @global
  - gem uninstall bundler -x || gem uninstall bundler -a || true
  - gem install bundler -v 1.17.3
  - bundler --version
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6523128341fad111ed79
    on_success: change
    on_failure: always
    on_start: never
